### ISSUE TITLE
Fix `.search-editor` styles

### ISSUE THREAD

**Issue by flourish86** [Icinga/ipl-web#26]
- [x] The selects do have the system appearance in Safari
- [x] The select's custom arrow icon is missing
- [x] The input styles should match the `.search-bar .term`s: segmented look
- [ ] maybe match `…` buttons style with the control buttons

**Comment by nilmerg** [comment]
> * [ ]  maybe match `…` buttons style with the control buttons

I don't think that's a good idea. They're not clickable just like the rest of the control buttons.
