### ISSUE TITLE
Search Editor UX Improvements

### ISSUE THREAD

**Issue by flourish86** [Icinga/ipl-web#33]
## Open the suggestions flyout, when focussing the filter input element

When the user (accidentally) closes the suggestions flyout and clicks (or focuses) the filter input again, it would be helpful to have the suggestions flyout appear again. This is how the pills behave as well.

## Consolidate `Tab` Key behavior

The tab key behaves differently depending on the suggestions flyout. 

a) With the suggestions flyout closed, `Tab` or `Shift + Tab` rotates between the pills, if at least one exists
b) When the flyout is open, `Tab` or `Shift + Tab` 

We should streamline that behavior and use the tabs for rotating between pills and have the arrow up/down keys for selecting the flyout items.

The following steps illustrate the problem

1) Go to IcingaDB > Hosts
2) Click the SearchBar to focus it
3) Type "Host" -> the flyout appears with multiple suggestions
4) Select one, e.g. "Host Name"
5) Hit enter, so the column pill for e.g. "Host Name" will be created
6) The text input will be focussed again and the flyout re-appears with suggestions for the operator. Fine so far

Behavior a)

This is the default behavior of the tab key

7) Select one of the operator suggestions -> The text input is focussed
8) Now the `Tab` (`Shift + Tab` respectively) key rotates between the pills

Behavior b)

7) The `Tab` Key now rotates through the suggestions, but there's no way to navigate back to the columns pill.

**Comment by nilmerg** [comment]
I don't see a suggested different behavior for the tab key or did I miss it?

a) and b) both describe the status-quo.

Btw.
> The Tab Key now rotates through the suggestions, but there's no way to navigate back to the columns pill.

Close the suggestions and you're back in the pill. And once on the last suggestion, pushing tab or arrow down should also focus the pill. As does shift+tab and arrow up on the very first suggestion.

**Comment by flourish86** [comment]
## Consolidate `Tab` Key behavior

> a) and b) both describe the status-quo.

Yes, as pointed out: 
> The following steps _illustrate the problem_ …

--

> I don't see a suggested different behavior for the tab key or did I miss it?

Sorry, if that wasn't clear enough, but it's there:

> We should streamline that behavior and use the [`Tab` key] for rotating between pills and have the arrow up/down keys for selecting the flyout items.

The different modal behavior produces mental overhead for the user, that we could avoid.

It's pretty common sense to avoid this problem in ui design and nothing devious. It is pretty well summarized for example in [this article](https://www.nngroup.com/articles/modes/):

> # Modes in User Interfaces 
> […]
> Definition: Modes are different interpretations of the user input by the system, depending on the state which is active. Same input, different results.

further:

> ### Common Mode Errors and Usability Problems
> 
> Modes can cause a range of usability problems, including mode slips (occurring when the user is not aware of the currently active mode) and low discoverability of mode-specific features.

**Comment by flourish86** [comment]
And by the way: The new Search Bar already works pretty well in general and improves the search experience a lot. But complex things like this are hard to nail on the first iteration. I'm just suggesting improvements, that may seem small, but in the end do make a difference for usability. 😉
